### ISSUE TITLE
python on Windows

### ISSUE THREAD

**Issue by howi42** [bwydoogh/domoticz-scripts#11]
This script causes me a lot of trouble , using it on Windows, like print statements ...
print "...."    
does not work, but
print (".....") does.

What else do I have to change to make this script run on Windows ?

**Comment by bwydoogh** [comment]
Hi. Is not related to _Windows_ but rather to the Python version you are using. I guess you are using version 3 (which you _should_ use ;-)) but my code is not ready for Python 3. 
Feel free to contribute (if not, I will see when I can do this as I am not actively using the script anymore).

**Comment by howi42** [comment]
Thanks for your answer, I see this now.
Found another project on Github, doing it for Python 3.0.
Works nicely.

QuentinCG/Milight-Wifi-Bridge-3.0-Python-Library
