### ISSUE TITLE
What is the <script location> ?

### ISSUE THREAD

**Issue by valentinoeval** [bwydoogh/domoticz-scripts#7]
I need to know from what directory are based <script location>. It's the scripts directory in domoticz dir or /home/pi/domoticz/scripts/domoticz-script/ ?

script:///<script location>/milight-home.sh ON

**Comment by bwydoogh** [comment]
Hi.

If you have installed domoticz in the home directory of the "pi" user, it is: script:///home/pi/domoticz/scripts/milight-home-trigger.sh ON

**Comment by valentinoeval** [comment]
Great ! Thank's ;)
