### ISSUE TITLE
Bedankt voor de inspiratie!

### ISSUE THREAD

**Issue by gerardwr** [bwydoogh/domoticz-scripts#9]
Hallo,

Met jouw python script als vliegende start heb ik een Arduino sketch voor de ESP8266 gemaakt die via een iBox mijn Milight lampen aan/uit schakelt.

Bedankt voor de inspiratie en het sharen van je code.

Gerard.

**Comment by bwydoogh** [comment]
Leuk te horen :). 

Succes verder in ieder geval!
